// ─────────────────────────────────────────────────────────────
//  IMPORTAR LEADS v2 — Andarilho Digital
//  Cole no console com pipeline-leads.html aberto
//  F12 → Console → "allow pasting" → colar → Enter
//  ✦ Atualiza leads existentes (por nome) + adiciona novos
// ─────────────────────────────────────────────────────────────

const novosLeads = [

  // ══════════════════════════════════════════════════════════
  //  CLÍNICAS DE BOTOX & HARMONIZAÇÃO FACIAL (26)
  // ══════════════════════════════════════════════════════════

  {
    nome: "Anne Aguiar Estética",
    nicho: "clínica", cidade: "Moema, São Paulo",
    whatsapp: "5511950061020",
    site: "anneaguiar.com.br",
    instagram: "@anneaguiar.estetica",
    canal: "whatsapp",
    problema: "Saiu do emprego em 2022 pra empreender sozinha — agenda 100% manual no WhatsApp",
    mensagem: `Oi Anne, tudo bem?\n\nVi seu trabalho em Moema — saiu do emprego pra empreender, isso já diz tudo.\n\nPergunta direta: o agendamento ainda é tudo pelo WhatsApp na mão? Porque é exatamente essa parte que mais toma tempo de quem atende sozinha.`,
    notas: "Tel: (11) 95006-1020 | Profissional solo desde 2022",
    presencaDigital: "tem site (anneaguiar.com.br) | @anneaguiar.estetica — perfil ativo | telefone no Google: (11) 95006-1020 | presença forte",
  },
  {
    nome: "Dra. Poly — Harmonização Facial",
    nicho: "clínica", cidade: "Moema, São Paulo",
    whatsapp: "5511969247340",
    site: "drapolyharmonizacaofacial.com.br",
    instagram: "@drapolyharmonizacaofacial",
    canal: "whatsapp",
    problema: "Mais de 11 anos de atuação, clientela grande — provável sobrecarga de atendimento manual",
    mensagem: `Oi! Vi seu trabalho em Moema — 11 anos de experiência, clientela consolidada.\n\nCurioso: com esse volume de pacientes, como você está gerenciando as confirmações de agenda? Ainda é manual ou já tem alguma automação?\n\nPergunto porque no-show em horário nobre é onde mais se perde.`,
    notas: "Sem telefone público | 11+ anos de atuação | contato só via DM",
    presencaDigital: "tem site (drapolyharmonizacaofacial.com.br) | @drapolyharmonizacaofacial | contato só via Instagram DM | sem reviews públicos visíveis | presença média",
  },
  {
    nome: "Dra. Vanessa Costa",
    nicho: "clínica", cidade: "Moema, São Paulo",
    whatsapp: "5511968869699",
    site: "",
    instagram: "@dravanessa.vcy",
    canal: "whatsapp",
    problema: "Dois números de WhatsApp listados — atendimento fragmentado, sinal de sobrecarga manual",
    mensagem: `Oi Vanessa, tudo bem?\n\nVi que você tem dois números de WhatsApp no perfil — isso geralmente significa atendimento dividido, o que acaba gerando resposta lenta e perda de agendamento.\n\nIsso ainda é gerenciado na mão ou já tem algum sistema?`,
    notas: "Tel: (11) 96886-9699 | Dois WhatsApps cadastrados — sinal de sobrecarga",
    presencaDigital: "sem site | @dravanessa.vcy — perfil ativo | telefone no Google: (11) 96886-9699 | dois números listados — atendimento fragmentado | presença média",
  },
  {
    nome: "Dr. Face Estética",
    nicho: "clínica", cidade: "Moema, São Paulo",
    whatsapp: "5511991080636",
    site: "",
    instagram: "@drfaceestetica",
    canal: "whatsapp",
    problema: "Clínica de 2017, múltiplos procedimentos — alto volume de contatos",
    mensagem: `Oi! Vi o trabalho do Dr. Face em Moema — estrutura sólida desde 2017.\n\nUma coisa que percebi: clínicas com esse volume de procedimentos geralmente têm muito lead chegando pelo Instagram e sumindo antes de agendar.\n\nVocês têm algum processo pra capturar esses contatos fora do horário?`,
    notas: "Tel: (11) 99108-0636 | Operando desde 2017",
    presencaDigital: "sem site | @drfaceestetica — perfil ativo | telefone no Google | ativa desde 2017 — volume alto provável | presença média",
  },
  {
    nome: "Madame Face",
    nicho: "clínica", cidade: "Moema, São Paulo",
    whatsapp: "5511913089597",
    site: "madameface.com.br",
    instagram: "@madamefacebr",
    canal: "whatsapp",
    problema: "Marca forte em rinomodelação — identidade premium, provável perda no follow-up",
    mensagem: `Oi! Vi o posicionamento da Madame Face — identidade visual forte, nicho bem definido em rinomodelação.\n\nCurioso: quando uma paciente manda DM perguntando sobre o procedimento, quanto tempo leva até ela receber resposta e de fato agendar?\n\nEsse intervalo é onde a maioria das clínicas perde paciente.`,
    notas: "Sem telefone público | marca premium em rinomodelação | contato só via DM ou site",
    presencaDigital: "tem site (madameface.com.br) | @madamefacebr — marca visível, identidade forte | contato só via Instagram DM ou formulário | presença média-forte",
  },
  {
    nome: "Dra. Carolina Macedo — Botox & Harmonização",
    nicho: "clínica", cidade: "Moema, São Paulo",
    whatsapp: "",
    site: "",
    instagram: "@dra.carolinamacedo",
    canal: "instagram",
    problema: "Biomédica com mestrado USP, perfil premium — perde no follow-up de retorno",
    mensagem: `Oi Carol! Vi seu trabalho — resultado limpo, clientela claramente exigente.\n\nPergunta direta: botox pede retorno a cada 4-6 meses. Você tem algum sistema que avisa a paciente quando está na hora de voltar, ou ainda depende dela lembrar sozinha?\n\nÉ exatamente isso que define se ela volta pra você ou vai pra concorrente.`,
    notas: "Sem telefone e sem site | Biomédica com mestrado USP | contato só via DM",
    presencaDigital: "sem site | @dra.carolinamacedo — perfil profissional ativo | contato só via Instagram DM | perfil premium sem canal direto de atendimento | presença fraca",
  },
  {
    nome: "Dra. Tatiana Pascual — Harmonização & Invisalign",
    nicho: "clínica", cidade: "Moema, São Paulo",
    whatsapp: "",
    site: "",
    instagram: "@dratatianapascual",
    canal: "instagram",
    problema: "Dentista + harmonização — dois serviços com retorno periódico, sem sistema de reativação",
    mensagem: `Oi Tatiana! Vi que você atende harmonização e Invisalign em Moema — dois serviços com retorno periódico natural.\n\nVocê tem algum sistema que avisa a paciente quando está na hora de retornar, ou ainda depende dela lembrar sozinha?\n\nPorque reativação automática nesses dois casos é receita previsível.`,
    notas: "Sem telefone e sem site | Dentista + harmonização — duplo ciclo de retorno | contato só via DM",
    presencaDigital: "sem site | @dratatianapascual — perfil ativo | contato só via Instagram DM | dois serviços com retorno periódico sem automação evidente | presença fraca",
  },
  {
    nome: "Clínica Estética Batel",
    nicho: "clínica", cidade: "Batel, Curitiba",
    whatsapp: "",
    site: "esteticabatel.com.br",
    instagram: "@clinicaesteticabatel",
    canal: "instagram",
    problema: "+1.866 avaliações positivas no Google — alto volume, provável sobrecarga de agendamento",
    mensagem: `Oi! Vi a Clínica Estética Batel no Google — quase 2000 avaliações, nota altíssima. Reputação sólida.\n\nCom esse volume de pacientes, como vocês estão gerenciando os agendamentos que chegam fora do horário?\n\nPergunto porque clínicas com essa demanda geralmente perdem mais de 20% dos leads só por demora na resposta.`,
    notas: "+1866 avaliações Google — alto volume | sem telefone público | contato via site ou DM",
    presencaDigital: "tem site (esteticabatel.com.br) | @clinicaesteticabatel | contato via site ou Instagram DM | +1866 avaliações Google — presença digital muito forte | presença forte",
  },
  {
    nome: "Face Doctor Água Verde",
    nicho: "clínica", cidade: "Água Verde, Curitiba",
    whatsapp: "5541997852727",
    site: "facedoctoraguaverde.com.br",
    instagram: "@facedoctoraguaverde",
    canal: "whatsapp",
    problema: "Clínica de rejuvenescimento e harmonização no Água Verde — bairro premium de Curitiba",
    mensagem: `Oi! Vi o Face Doctor no Água Verde — procedimentos de alto padrão, bairro exigente.\n\nUma coisa que clínicas premium frequentemente perdem: paciente novo entra pelo Instagram à noite, não recebe resposta rápida, vai pra concorrente.\n\nIsso está sendo gerenciado de forma automatizada ou ainda é manual?`,
    notas: "Sem telefone público | bairro premium Água Verde CWB | contato via site ou DM",
    presencaDigital: "tem site (facedoctoraguaverde.com.br) | @facedoctoraguaverde | contato só via Instagram DM ou formulário | bairro nobre — clientela exigente com tempo de resposta curto | presença média",
  },
  {
    nome: "Perfeccionare Estética Curitiba",
    nicho: "clínica", cidade: "Curitiba",
    whatsapp: "5541999908946",
    site: "",
    instagram: "@perfeccionare_curitiba",
    canal: "whatsapp",
    problema: "Harmonização facial e corporal — múltiplos procedimentos, alto volume de DMs",
    mensagem: `Oi! Vi o trabalho da Perfeccionare — portfólio amplo de procedimentos.\n\nCurioso: quando uma paciente manda DM fora do horário perguntando sobre valores ou disponibilidade, o que acontece com esse contato?\n\nÉ exatamente aí que a maioria das clínicas perde lead sem perceber.`,
    notas: "Sem telefone e sem site | só Instagram | contato exclusivo via DM",
    presencaDigital: "sem site | @perfeccionare_curitiba — perfil ativo | contato só via Instagram DM | sem canal alternativo — 100% dependente de DM | presença fraca",
  },
  {
    nome: "Royal Face Batel",
    nicho: "clínica", cidade: "Batel, Curitiba",
    whatsapp: "",
    site: "",
    instagram: "@royalface.batel",
    canal: "instagram",
    problema: "Rede com unidade no Batel — oferece avaliação gratuita, alto volume de contatos para gerenciar",
    mensagem: `Oi! Vi que a Royal Face Batel oferece avaliação gratuita — estratégia inteligente pra Curitiba.\n\nCom o volume de contatos que isso gera, como vocês estão fazendo o follow-up de quem pediu avaliação mas não agendou?\n\nEsse é geralmente o maior gap de receita em clínicas que usam avaliação como isca.`,
    notas: "Sem telefone e sem site | avaliação gratuita como isca — alto volume | contato via DM",
    presencaDigital: "sem site próprio | @royalface.batel — unidade local de rede | contato só via Instagram DM | estratégia de avaliação gratuita gera volume alto sem sistema de follow-up evidente | presença fraca",
  },
  {
    nome: "HOF Clinic Curitiba",
    nicho: "clínica", cidade: "Batel, Curitiba",
    whatsapp: "",
    site: "",
    instagram: "@hofclinic.curitiba",
    canal: "instagram",
    problema: "Se declara maior clínica de harmonização do Batel — alto volume garantido",
    mensagem: `Oi! Vi a HOF Clinic no Batel — referência em harmonização na região.\n\nUma pergunta direta: com esse volume de atendimento, vocês já têm automação de confirmação de agenda e follow-up de retorno, ou ainda é processo manual?\n\nPergunto porque é exatamente onde clínicas grandes vazam receita.`,
    notas: "Sem telefone e sem site | referência no Batel | contato via DM",
    presencaDigital: "sem site próprio | @hofclinic.curitiba — unidade local | se posiciona como a maior do Batel | contato só via Instagram DM | presença fraca em canal próprio",
  },
  {
    nome: "Dra. Stephany Ellen",
    nicho: "clínica", cidade: "Água Verde, Curitiba",
    whatsapp: "",
    site: "drastephanyellen.com.br",
    instagram: "@drastephanyellen",
    canal: "instagram",
    problema: "+600 tratamentos em 6 anos — profissional solo com volume crescente",
    mensagem: `Oi Stephany! Vi mais de 600 tratamentos em 6 anos — ritmo forte para quem atende sozinha.\n\nCom esse crescimento, o agendamento ainda passa tudo pelo WhatsApp na mão?\n\nPorque a partir de certo volume, o processo manual começa a limitar o crescimento em vez de acompanhá-lo.`,
    notas: "Sem telefone | +600 tratamentos / 6 anos | solo | contato via site ou DM",
    presencaDigital: "tem site (drastephanyellen.com.br) | @drastephanyellen — +600 tratamentos documentados | contato só via Instagram DM ou formulário | solo com volume crescente — risco de gargalo manual | presença média",
  },
  {
    nome: "Odonto Dornelles",
    nicho: "clínica", cidade: "Auxiliadora, Porto Alegre",
    whatsapp: "",
    site: "",
    instagram: "@odontodornelles",
    canal: "instagram",
    problema: "Dentista com harmonização facial na Auxiliadora — retorno periódico sem sistema de reativação",
    mensagem: `Oi! Vi o trabalho da Odonto Dornelles na Auxiliadora — harmonização e odontologia no mesmo espaço.\n\nPaciente de harmonização volta a cada 4-6 meses, paciente de odonto anualmente. Vocês têm algum sistema que faz esse lembrete automaticamente ou ainda é manual?\n\nReativação automática nesses casos é receita previsível e quase zero esforço.`,
    notas: "Sem telefone e sem site | dentista + harmonização | bairro nobre POA | contato via DM",
    presencaDigital: "sem site | @odontodornelles — combo odonto + harmonização | contato só via Instagram DM | dois ciclos de retorno sem sistema evidente | presença fraca",
  },
  {
    nome: "Clínica Formosa",
    nicho: "clínica", cidade: "Auxiliadora, Porto Alegre",
    whatsapp: "5551995905945",
    site: "clinicaformosa.com",
    instagram: "@clinicaformosa",
    canal: "whatsapp",
    problema: "Clínica em bairro nobre de POA — alta demanda, provável processo de agendamento manual",
    mensagem: `Oi! Vi a Clínica Formosa na Auxiliadora — região nobre, clientela exigente.\n\nUma coisa que percebi em clínicas bem posicionadas como a de vocês: o maior problema raramente é captação — é o lead que chegou, não foi atendido rápido o suficiente e foi embora.\n\nIsso está sendo gerenciado com alguma automação ou ainda é na mão?`,
    notas: "Sem telefone | bairro Auxiliadora POA | contato via site ou DM",
    presencaDigital: "tem site (clinicaformosa.com) | @clinicaformosa — bairro nobre, clientela exigente | contato via Instagram DM ou formulário no site | bairro premium com expectativa de resposta rápida | presença média",
  },
  {
    nome: "Dra. Luisa Giacomini",
    nicho: "clínica", cidade: "Independência, Porto Alegre",
    whatsapp: "5551996297060",
    site: "luisagiacomini.com.br",
    instagram: "@luisagiacomini",
    canal: "whatsapp",
    problema: "Estética avançada e harmonização — profissional com site próprio, sem automação de atendimento",
    mensagem: `Oi Luisa! Vi seu site — posicionamento claro em estética avançada, público seleto.\n\nUma pergunta: com esse perfil de clientela, a confirmação de agenda e o follow-up de retorno ainda são feitos manualmente?\n\nÉ exatamente o tipo de processo que, automatizado, libera seu tempo pra focar no que dá dinheiro.`,
    notas: "Sem telefone | site profissional próprio | bairro Independência POA",
    presencaDigital: "tem site (luisagiacomini.com.br) — profissional próprio | @luisagiacomini — estética avançada | contato só via Instagram DM ou formulário | solo com posicionamento premium | presença média",
  },
  {
    nome: "Dra. Alessandra Drummond",
    nicho: "clínica", cidade: "Ipanema, Rio de Janeiro",
    whatsapp: "552122745535",
    site: "alessandradrummond.com.br",
    instagram: "@dra.alessandradrummond",
    canal: "whatsapp",
    problema: "Dermatologista com botox em Ipanema e Barra — dois consultórios, alto volume",
    mensagem: `Oi Alessandra! Vi seu trabalho em Ipanema e Barra — dois consultórios é volume alto pra gerenciar.\n\nCom atendimento em dois pontos, como está sendo feito o controle de agendamentos e confirmações? Ainda é manual em cada unidade?\n\nÉ exatamente esse gap que gera no-show e perda de receita em clínicas com mais de uma unidade.`,
    notas: "Tel: (21) 2274-5535 | dois consultórios: Ipanema e Barra | dermatologista + botox",
    presencaDigital: "tem site (alessandradrummond.com.br) | @dra.alessandradrummond | telefone no Google: (21) 2274-5535 | dois consultórios — volume alto e processo fragmentado | presença forte",
  },
  {
    nome: "Dra. Renata Deschamps",
    nicho: "clínica", cidade: "Ipanema, Rio de Janeiro",
    whatsapp: "",
    site: "drarenatadeschamps.com.br",
    instagram: "@drarenatadeschamps",
    canal: "instagram",
    problema: "Cirurgiã-dentista com harmonização orofacial em Ipanema — perfil premium, retorno periódico",
    mensagem: `Oi Renata! Vi seu trabalho em Ipanema — harmonização orofacial de alto padrão.\n\nUma coisa que profissionais como você frequentemente perdem: paciente de harmonização pede retorno a cada 4-6 meses. Você tem algum sistema que faz esse lembrete ou ainda depende da paciente lembrar?\n\nÉ receita garantida que escapa por falta de processo.`,
    notas: "Sem telefone | cirurgiã-dentista + harmonização | Ipanema | contato via site ou DM",
    presencaDigital: "tem site (drarenatadeschamps.com.br) | @drarenatadeschamps — Ipanema, alto padrão | contato só via Instagram DM ou formulário | retorno periódico sem sistema evidente | presença média",
  },
  {
    nome: "Dr. Fabio Barros",
    nicho: "clínica", cidade: "Ipanema, Rio de Janeiro",
    whatsapp: "5521999120014",
    site: "drfabiobarros.com.br",
    instagram: "@drfabiobarros",
    canal: "whatsapp",
    problema: "Harmonização e rejuvenescimento em Ipanema — público premium, alto ticket",
    mensagem: `Oi Fabio! Vi seu trabalho em Ipanema — bioestimuladores, fios e preenchimento de alto padrão.\n\nPergunta direta: paciente que fez bioestimulador volta em 6-12 meses. Você tem algum processo automático que avisa esse retorno ou ainda é na lembrança?\n\nEm ticket alto, cada retorno perdido é R$1.500-3.000 que vai pra concorrente.`,
    notas: "Sem telefone | bioestimuladores + fios — ticket alto | Ipanema | contato via site ou DM",
    presencaDigital: "tem site (drfabiobarros.com.br) | @drfabiobarros — bioestimuladores, fios, preenchimento | contato só via Instagram DM ou formulário | ticket alto sem sistema de reativação evidente | presença média",
  },
  {
    nome: "Mealth Clinic",
    nicho: "clínica", cidade: "Barra da Tijuca, Rio de Janeiro",
    whatsapp: "5521975333689",
    site: "mealthclinic.com.br",
    instagram: "@mealthclinic",
    canal: "whatsapp",
    problema: "Clínica com duas unidades no RJ — Barra e Cachambi, alto volume operacional",
    mensagem: `Oi! Vi a Mealth Clinic — duas unidades no RJ, estrutura sólida.\n\nCom esse volume, como vocês estão fazendo a gestão de leads que chegam pelo WhatsApp e Instagram em cada unidade?\n\nClínicas com múltiplas unidades geralmente perdem muito no gap entre o contato e o agendamento efetivo.`,
    notas: "Sem telefone | duas unidades: Barra e Cachambi | contato via site ou DM",
    presencaDigital: "tem site (mealthclinic.com.br) | @mealthclinic — duas unidades no RJ | contato via Instagram DM ou formulário | gestão de leads em duas unidades sem automação evidente | presença média-forte",
  },
  {
    nome: "Dra. Adriana Koeppel",
    nicho: "clínica", cidade: "Savassi, Belo Horizonte",
    whatsapp: "553132819482",
    site: "draadrianakoeppel.com.br",
    instagram: "@draadrianakoeppel",
    canal: "whatsapp",
    problema: "Referência em harmonização no Savassi — bairro premium de BH, alto volume de DMs",
    mensagem: `Oi Adriana! Vi seu trabalho no Savassi — referência clara em harmonização na região.\n\nCom esse posicionamento, imagino que chegam bastante contatos pelo Instagram e WhatsApp diariamente. Esse atendimento inicial ainda é manual ou já tem alguma automação?\n\nPergunto porque é exatamente onde clínicas bem posicionadas vazam mais lead.`,
    notas: "Tel: (31) 3281-9482 | referência Savassi BH | site + Instagram + telefone — presença completa",
    presencaDigital: "tem site (draadrianakoeppel.com.br) | @draadrianakoeppel — referência no Savassi | telefone no Google: (31) 3281-9482 | presença completa — alta demanda sem automação evidente | presença forte",
  },
  {
    nome: "Clínica Nicole Chaib",
    nicho: "clínica", cidade: "Lourdes, Belo Horizonte",
    whatsapp: "5531999015959",
    site: "clinicachaib.com",
    instagram: "@clinicachaib",
    canal: "whatsapp",
    problema: "Dentista com harmonização orofacial em Lourdes — bairro nobre de BH",
    mensagem: `Oi Nicole! Vi a clínica em Lourdes — harmonização de alto padrão, bairro seleto.\n\nUma pergunta: com perfil de clientela como o de vocês, a confirmação de agenda e o follow-up de retorno de botox ainda são feitos na mão?\n\nÉ o tipo de processo que automatizado libera tempo e garante receita recorrente.`,
    notas: "Sem telefone | dentista + harmonização | bairro Lourdes BH | contato via site ou DM",
    presencaDigital: "tem site (clinicachaib.com) | @clinicachaib — harmonização orofacial em Lourdes | contato via Instagram DM ou formulário | bairro nobre sem canal de resposta rápida evidente | presença média",
  },
  {
    nome: "Estetic Doctor BH",
    nicho: "clínica", cidade: "Belo Horizonte",
    whatsapp: "",
    site: "",
    instagram: "@esteticdoctorbh",
    canal: "instagram",
    problema: "Botox e harmonização em BH — perfil ativo no Instagram, sem canal de atendimento rápido",
    mensagem: `Oi! Vi o trabalho do Estetic Doctor — botox e harmonização com boa presença no Instagram.\n\nCurioso: quando paciente novo manda DM perguntando sobre valor ou disponibilidade, quanto tempo leva até virar consulta agendada?\n\nEsse tempo de resposta é o maior fator de perda de lead em clínicas com boa audiência.`,
    notas: "Sem telefone e sem site | só Instagram | presença 100% via DM",
    presencaDigital: "sem site | @esteticdoctorbh — ativo no Instagram | contato exclusivo via DM | sem canal alternativo — 100% dependente de resposta manual no Instagram | presença fraca",
  },
  {
    nome: "Instituto Valeska Guerra",
    nicho: "clínica", cidade: "Belo Horizonte",
    whatsapp: "5531996649631",
    site: "valeskaguerra.com.br",
    instagram: "@valeskaguerra",
    canal: "whatsapp",
    problema: "Instituto de estética avançada em BH — marca consolidada, retorno periódico sem automação",
    mensagem: `Oi Valeska! Vi o Instituto — estética avançada, marca bem construída em BH.\n\nUma coisa que institutos com seu posicionamento frequentemente deixam na mesa: o follow-up de retorno de cada procedimento ainda é manual?\n\nBioestimulador, botox e fios têm janela de retorno clara — automação disso é receita garantida.`,
    notas: "Sem telefone | marca Instituto consolidada | site próprio | contato via site ou DM",
    presencaDigital: "tem site (valeskaguerra.com.br) | @valeskaguerra — Instituto consolidado em BH | contato só via Instagram DM ou formulário | marca forte sem sistema de reativação evidente | presença média-forte",
  },
  {
    nome: "Hamonir Estética",
    nicho: "clínica", cidade: "Campinas",
    whatsapp: "5519998622205",
    site: "hamonir.com.br",
    instagram: "@hamonircampinasleste",
    canal: "whatsapp",
    problema: "Clínica de estética em Campinas Leste — cidade grande, mercado em expansão",
    mensagem: `Oi! Vi a Hamonir em Campinas — estética avançada numa das maiores cidades do interior.\n\nPergunta direta: o atendimento inicial no WhatsApp ainda é manual? Campinas tem muito concorrente — quem responde mais rápido geralmente fica com o lead.\n\nTem alguma automação nisso hoje?`,
    notas: "Tel: (19) 99862-2205 | site + Instagram + telefone | Campinas Leste",
    presencaDigital: "tem site (hamonir.com.br) | @hamonircampinasleste | telefone no Google: (19) 99862-2205 | mercado de Campinas competitivo — tempo de resposta crítico | presença forte",
  },
  {
    nome: "Perfeccionare Estética Florianópolis",
    nicho: "clínica", cidade: "Florianópolis",
    whatsapp: "5548999915629",
    site: "perfeccionareclinica.com.br",
    instagram: "@perfeccionareclinica",
    canal: "whatsapp",
    problema: "Harmonização facial e corporal em Floripa — cidade turística com clientela exigente",
    mensagem: `Oi! Vi a Perfeccionare em Florianópolis — harmonização facial e corporal, clientela exigente de cidade turística.\n\nUma coisa que chama atenção: clínicas em Floripa atendem muito paciente sazonal que pesquisa antes de chegar. Vocês têm algum processo automático de atendimento fora do horário?\n\nÉ onde boa parte dos leads turísticos se perde.`,
    notas: "Sem telefone | Florianópolis — clientela turística e local | site próprio | contato via site ou DM",
    presencaDigital: "tem site (perfeccionareclinica.com.br) | @perfeccionareclinica | contato via Instagram DM ou formulário | mercado turístico — leads pesquisam fora do horário | presença média",
  },

  // ══════════════════════════════════════════════════════════
  //  PET SHOPS (26)
  // ══════════════════════════════════════════════════════════

  {
    nome: "Amor de Bicho",
    nicho: "pet shop", cidade: "Jardim da Saúde, São Paulo",
    whatsapp: "",
    site: "banhoetosajardimdasaude.com.br",
    instagram: "@amordebichosp",
    canal: "instagram",
    problema: "Site próprio mas contato via formulário — maioria dos tutores prefere WhatsApp",
    mensagem: `Oi! Vi que o Amor de Bicho tem site próprio — já é diferencial no bairro.\n\nUma coisa que percebi: o contato no site é por formulário, mas a maioria dos tutores prefere WhatsApp. Vocês têm muito contato chegando lá que não vira agendamento?\n\nÉ exatamente onde banho e tosa perde cliente sem perceber.`,
    notas: "Sem telefone | site com formulário — maioria vai pelo WA | contato via site ou DM",
    presencaDigital: "tem site (banhoetosajardimdasaude.com.br) — contato via formulário | @amordebichosp | contato via Instagram DM ou formulário | canal principal do tutor é WhatsApp, não formulário | presença média",
  },
  {
    nome: "Fórmula Pet 24hs",
    nicho: "pet shop", cidade: "Moema, São Paulo",
    whatsapp: "",
    site: "formulapet24hs.com.br",
    instagram: "@formulapet24hs",
    canal: "instagram",
    problema: "Atende 24hs — diferencial forte mas sem automação de resposta fora do horário",
    mensagem: `Oi! Vi que a Fórmula Pet opera 24hs em Moema — diferencial forte.\n\nMas uma pergunta: quem responde o WhatsApp às 2h da manhã quando tutor quer agendar banho pra semana?\n\nSe ainda é manual, vocês estão perdendo agendamento em horário que vocês mesmos criaram como diferencial.`,
    notas: "Operação 24hs | sem telefone público | site próprio | contato via site ou DM",
    presencaDigital: "tem site (formulapet24hs.com.br) | @formulapet24hs — 24hs como diferencial | contato via Instagram DM ou formulário | operam 24hs mas sem automação de atendimento evidente — contradição | presença média",
  },
  {
    nome: "Bable Pet",
    nicho: "pet shop", cidade: "São Paulo",
    whatsapp: "5511972383531",
    site: "bablepet.com.br",
    instagram: "@bablepet",
    canal: "whatsapp",
    problema: "Pet shop completo em SP — alto volume, processo de agendamento manual",
    mensagem: `Oi! Vi a Bable Pet — estrutura completa, posicionamento forte.\n\nUma pergunta: quando tutor manda mensagem pedindo horário de banho fora do expediente, o que acontece com esse pedido?\n\nÉ onde a maioria dos pet shops perde agendamento sem nem saber.`,
    notas: "Sem telefone | site próprio | SP capital | contato via site ou DM",
    presencaDigital: "tem site (bablepet.com.br) | @bablepet — pet shop completo em SP | contato via Instagram DM ou formulário | SP — mercado altamente competitivo, tempo de resposta decisivo | presença média",
  },
  {
    nome: "Pet Bosque Saúde",
    nicho: "pet shop", cidade: "Saúde, São Paulo",
    whatsapp: "",
    site: "petbosquesaude.com",
    instagram: "@petbosquesaude",
    canal: "instagram",
    problema: "Pet shop de bairro em São Paulo — clientela recorrente sem sistema de reativação",
    mensagem: `Oi! Vi o Pet Bosque Saúde — pet shop de bairro com presença digital.\n\nPergunta direta: vocês têm algum sistema que lembra o tutor quando está na hora do próximo banho? Cachorro de médio porte precisa a cada 15-21 dias.\n\nSe o lembrete ainda é manual, vocês estão deixando receita recorrente na mesa toda semana.`,
    notas: "Sem telefone | site próprio | bairro Saúde SP | clientela recorrente",
    presencaDigital: "tem site (petbosquesaude.com) | @petbosquesaude | contato via Instagram DM ou formulário | clientela de bairro com ciclo recorrente — sem sistema de lembrete evidente | presença média",
  },
  {
    nome: "Pet Batel",
    nicho: "pet shop", cidade: "Batel, Curitiba",
    whatsapp: "",
    site: "",
    instagram: "@petbatel",
    canal: "instagram",
    problema: "Pet shop no bairro mais nobre de Curitiba — clientela premium, alto ticket",
    mensagem: `Oi! Vi o Pet Batel — pet shop no Batel, clientela claramente premium.\n\nUma coisa que pet shops em bairro nobre geralmente perdem: tutor de raça pura tem ciclo certo de banho e tosa. Vocês têm algum sistema de lembrete automático pra esses clientes?\n\nRecorrência automática em bairro premium é o produto mais valioso que existe.`,
    notas: "Sem telefone e sem site | bairro Batel CWB — mais nobre da cidade | contato exclusivo via DM",
    presencaDigital: "sem site | @petbatel — Batel, bairro nobre de CWB | contato exclusivo via Instagram DM | clientela premium sem sistema de recorrência evidente | presença fraca",
  },
  {
    nome: "Dog Spa Curitiba",
    nicho: "pet shop", cidade: "Curitiba",
    whatsapp: "",
    site: "",
    instagram: "@dogspa_curitiba",
    canal: "instagram",
    problema: "Especializado em tosa de raça (Golden, Spitz) — ticket alto, cliente recorrente sem follow-up",
    mensagem: `Oi! Vi o trabalho de vocês com tosa de raça — Golden, Spitz, qualidade clara.\n\nEsse tipo de serviço tem cliente recorrente com intervalo certo (Golden a cada 6-8 semanas). Vocês têm algum sistema que avisa o tutor quando está chegando a hora?\n\nSe não, esse lembrete sai da cabeça do tutor — e ele pode ir pra qualquer outro.`,
    notas: "Sem telefone e sem site | especialidade em raça — ticket alto | contato exclusivo via DM",
    presencaDigital: "sem site | @dogspa_curitiba — especialidade em tosa de raça | contato exclusivo via Instagram DM | nicho de alto ticket com ciclo preciso sem follow-up evidente | presença fraca",
  },
  {
    nome: "4Pets Curitiba",
    nicho: "pet shop", cidade: "Portão, Curitiba",
    whatsapp: "",
    site: "",
    instagram: "@4petscuritiba",
    canal: "instagram",
    problema: "Creche, hotel, loja e banho/tosa — múltiplos serviços, alto volume de agendamentos",
    mensagem: `Oi! Vi a 4Pets no Portão — creche, hotel, loja e banho tudo no mesmo lugar. Operação grande.\n\nCom esse volume de serviços diferentes, o agendamento ainda é tudo pelo WhatsApp na mão?\n\nÉ exatamente o tipo de operação que mais perde com processo manual — muita coisa pra lembrar, pouco sistema pra ajudar.`,
    notas: "Sem telefone e sem site | 4 serviços diferentes | operação grande | contato via DM",
    presencaDigital: "sem site | @4petscuritiba — creche, hotel, loja, banho | contato exclusivo via Instagram DM | operação complexa com múltiplos serviços sem sistema de triagem evidente | presença fraca",
  },
  {
    nome: "Puppys Pet Shop",
    nicho: "pet shop", cidade: "Tatuquara, Curitiba",
    whatsapp: "",
    site: "",
    instagram: "@puppyspetshop",
    canal: "instagram",
    problema: "Pet shop de bairro, atendimento via WhatsApp — lead perdido fora do horário",
    mensagem: `Oi! Vi o Puppys no Tatuquara — pet shop de bairro com boa presença no Instagram.\n\nPergunta direta: quando tutor manda mensagem pedindo horário de banho depois das 18h, o que acontece com esse pedido?\n\nÉ onde pet shop de bairro perde mais cliente — não por falta de qualidade, mas por falta de resposta rápida.`,
    notas: "Sem telefone e sem site | bairro Tatuquara CWB | contato exclusivo via DM",
    presencaDigital: "sem site | @puppyspetshop | contato exclusivo via Instagram DM | pet shop de bairro sem sistema de atendimento fora do horário | presença fraca",
  },
  {
    nome: "Pet Focinho",
    nicho: "pet shop", cidade: "Asa Norte, Brasília",
    whatsapp: "5561991104004",
    site: "",
    instagram: "@petfocinho",
    canal: "whatsapp",
    problema: "Anuncia agendamento online 24h mas provável falta de confirmação automática e anti no-show",
    mensagem: `Oi! Vi que o Pet Focinho já tem agendamento online 24h — boa iniciativa, pouca gente faz isso.\n\nUma pergunta: quando alguém agenda, o tutor recebe confirmação automática pelo WhatsApp? E tem lembrete no dia anterior?\n\nSem isso, agendamento online vira no-show em silêncio.`,
    notas: "Tel: (61) 99110-4004 | Asa Norte BSB | agendamento online — sem confirmação automática evidente",
    presencaDigital: "sem site próprio | @petfocinho — anuncia 24h online | telefone no Google: (61) 99110-4004 | agendamento online sem confirmação/lembrete automático = no-show | presença média",
  },
  {
    nome: "Pet Shop Agrovillari",
    nicho: "pet shop", cidade: "Glória, Porto Alegre",
    whatsapp: "5551992687806",
    site: "agrovillari.com.br",
    instagram: "@agrovillari",
    canal: "whatsapp",
    problema: "Tele entrega de ração + banho e tosa — dois canais de atendimento, alto volume",
    mensagem: `Oi! Vi a Agrovillari — ração, acessórios e banho tudo junto em Porto Alegre.\n\nCom tele entrega e banho ao mesmo tempo, imagino que chegam bastante mensagens no WhatsApp por dia. Esse atendimento ainda é tudo na mão?\n\nÉ exatamente onde um atendente automático libera tempo do dono pra focar em crescer.`,
    notas: "Tel: (51) 99268-7806 | tele entrega + banho/tosa | site próprio | Glória POA",
    presencaDigital: "tem site (agrovillari.com.br) | @agrovillari | telefone no Google: (51) 99268-7806 | tele entrega + banho = volume duplo de contatos | presença forte",
  },
  {
    nome: "Pet Shop Molecão Matriz",
    nicho: "pet shop", cidade: "Glória, Porto Alegre",
    whatsapp: "5551995761203",
    site: "",
    instagram: "@petshopmolecao_matriz",
    canal: "whatsapp",
    problema: "Dois números de WhatsApp listados — atendimento fragmentado",
    mensagem: `Oi, tudo bem? Me chamo Guilherme, trabalho com automação para pet shops.\n\nVi que o Pet Molecão tem dois números de WhatsApp — isso geralmente significa atendimento dividido, que acaba gerando resposta lenta e perda de agendamento.\n\nVocês estão conseguindo acompanhar bem os pedidos de banho e tosa que chegam fora do horário?`,
    notas: "Tel: (51) 99576-1203 | dois WhatsApps — atendimento fragmentado | Glória POA",
    presencaDigital: "sem site | @petshopmolecao_matriz | telefone no Google: (51) 99576-1203 | dois números de atendimento — fragmentação de canal | presença média",
  },
  {
    nome: "Bichos e Caprichos",
    nicho: "pet shop", cidade: "Porto Alegre",
    whatsapp: "5551992858500",
    site: "",
    instagram: "@bichosecaprichospoa",
    canal: "whatsapp",
    problema: "Pet shop com banho e tosa — sem sistema de reativação para clientela recorrente",
    mensagem: `Oi! Vi os Bichos e Caprichos em Porto Alegre — boa presença no Instagram.\n\nUma pergunta rápida: vocês têm algum sistema que lembra o tutor quando está na hora do próximo banho?\n\nSe não tem, estão deixando receita recorrente na mesa toda semana — é o tipo de coisa simples que muda o faturamento.`,
    notas: "Tel: (51) 99285-8500 | sem site | POA",
    presencaDigital: "sem site | @bichosecaprichospoa | telefone no Google: (51) 99285-8500 | clientela recorrente sem lembrete automático evidente | presença média",
  },
  {
    nome: "Pet Place POA",
    nicho: "pet shop", cidade: "Porto Alegre",
    whatsapp: "",
    site: "",
    instagram: "@petplacepoa",
    canal: "instagram",
    problema: "Pet shop com banho e tosa — horário limitado, perde lead fora do expediente",
    mensagem: `Oi! Vi o Pet Place em Porto Alegre — banho e tosa com boa avaliação.\n\nCom horário comercial até às 19h, o que acontece com as mensagens que chegam depois disso pedindo agendamento?\n\nÉ onde a maioria dos pet shops perde cliente todo dia sem perceber.`,
    notas: "Sem telefone e sem site | POA | contato exclusivo via DM",
    presencaDigital: "sem site | @petplacepoa | contato exclusivo via Instagram DM | horário comercial limitado sem resposta automática fora do expediente | presença fraca",
  },
  {
    nome: "Agropet Store",
    nicho: "pet shop", cidade: "Porto Alegre",
    whatsapp: "",
    site: "",
    instagram: "@agropetpoa",
    canal: "instagram",
    problema: "Pet shop com vet 24 horas — alto volume, triagem de urgência ainda manual",
    mensagem: `Oi! Vi a Agropet Store — pet shop com vet 24h em Porto Alegre. Estrutura completa.\n\nCom vet 24h, imagino que chegam mensagens a qualquer hora. Como vocês estão triando o que é urgência veterinária do que é só agendamento de banho?\n\nSe ainda é manual, tem uma solução simples que resolve isso.`,
    notas: "Sem telefone e sem site | vet 24h — triagem manual | contato via DM",
    presencaDigital: "sem site | @agropetpoa — vet 24h + pet shop | contato exclusivo via Instagram DM | triagem de urgência manual a qualquer hora | presença fraca",
  },
  {
    nome: "ZIH Pet Store",
    nicho: "pet shop", cidade: "Belém Novo, Porto Alegre",
    whatsapp: "5551991062299",
    site: "",
    instagram: "@zihpetstore",
    canal: "whatsapp",
    problema: "Pet shop de bairro — atendimento via WhatsApp, sem follow-up pós-atendimento",
    mensagem: `Oi! Vi a ZIH Pet Store em Belém Novo — boa presença.\n\nPergunta direta: quando tutor manda mensagem pedindo horário de banho depois que vocês fecham, o que acontece com esse contato?\n\nÉ onde pet shop de bairro perde mais agendamento — não por falta de qualidade, por falta de resposta rápida.`,
    notas: "Tel: (51) 99106-2299 | Belém Novo POA | sem site",
    presencaDigital: "sem site | @zihpetstore | telefone no Google: (51) 99106-2299 | sem resposta automática fora do horário evidente | presença média",
  },
  {
    nome: "Puppyshow",
    nicho: "pet shop", cidade: "Porto Alegre",
    whatsapp: "5551302367877",
    site: "puppyshow.com.br",
    instagram: "@puppyshowpoa",
    canal: "whatsapp",
    problema: "Pet shop completo com veterinária, estética e creche — múltiplos serviços, triagem manual",
    mensagem: `Oi! Vi a Puppyshow em Porto Alegre — veterinária, estética, creche e farmácia. Operação completa.\n\nCom tantos serviços diferentes chegando pelo WhatsApp, como vocês estão organizando e priorizando cada tipo de contato?\n\nÉ exatamente o tipo de operação que mais se beneficia de automação de triagem e agendamento.`,
    notas: "Sem telefone | site próprio | vet + estética + creche + farmácia | contato via site ou DM",
    presencaDigital: "tem site (puppyshow.com.br) | @puppyshowpoa — estrutura completa | contato via Instagram DM ou formulário | 4 serviços distintos chegando pelo mesmo canal — triagem manual ineficiente | presença média-forte",
  },
  {
    nome: "Pet & Gatô Pet Shop",
    nicho: "pet shop", cidade: "Porto Alegre",
    whatsapp: "",
    site: "",
    instagram: "@petegatopetshop",
    canal: "instagram",
    problema: "Pet shop em Porto Alegre — clientela recorrente sem lembrete de retorno",
    mensagem: `Oi! Vi o Pet & Gatô em Porto Alegre — boa presença digital.\n\nUma coisa de curiosidade: vocês têm algum sistema que avisa o tutor quando está na hora do próximo banho?\n\nEm pet shop com clientela fiel, esse lembrete automático é o que separa receita previsível de receita que depende do tutor lembrar.`,
    notas: "Sem telefone e sem site | POA | contato exclusivo via DM",
    presencaDigital: "sem site | @petegatopetshop | contato exclusivo via Instagram DM | clientela fiel sem sistema de lembrete automático | presença fraca",
  },
  {
    nome: "Tchutchucão Pet Shop",
    nicho: "pet shop", cidade: "Porto Alegre",
    whatsapp: "555132269251",
    site: "",
    instagram: "@tchutchucao",
    canal: "whatsapp",
    problema: "Pet shop e consultório veterinário — ciclos de retorno diferentes sem sistema único",
    mensagem: `Oi! Vi o Tchutchucão — pet shop e consultório veterinário juntos em Porto Alegre.\n\nDois serviços com ciclo de retorno bem diferente: banho a cada 2-3 semanas, consulta veterinária quando precisa.\n\nVocês têm algum sistema que gerencia esses retornos automaticamente ou ainda é tudo na mão?`,
    notas: "Tel: (51) 3226-9251 | pet shop + vet | dois ciclos de retorno | POA",
    presencaDigital: "sem site | @tchutchucao | telefone no Google: (51) 3226-9251 | combo pet shop + vet — dois ciclos de retorno sem sistema integrado | presença média",
  },
  {
    nome: "Pet Store Rio",
    nicho: "pet shop", cidade: "Rio de Janeiro",
    whatsapp: "5521987996692",
    site: "",
    instagram: "@petstorerio",
    canal: "whatsapp",
    problema: "Pet shop no RJ com WhatsApp ativo — agendamento manual sem confirmação automática",
    mensagem: `Oi! Vi o Pet Store Rio — boa estrutura com WhatsApp de atendimento.\n\nPergunta direta: quando tutor manda mensagem pedindo horário de banho fora do expediente, o que acontece com esse contato?\n\nÉ onde pet shop no Rio perde mais agendamento — não por falta de qualidade, por falta de resposta rápida.`,
    notas: "Tel: (21) 98799-6692 | sem site | RJ",
    presencaDigital: "sem site | @petstorerio | telefone no Google: (21) 98799-6692 | sem resposta automática fora do horário evidente | presença média",
  },
  {
    nome: "Pet Harmony Barra",
    nicho: "pet shop", cidade: "Barra da Tijuca, Rio de Janeiro",
    whatsapp: "5521990357191",
    site: "",
    instagram: "@petharmonyloja",
    canal: "whatsapp",
    problema: "Banho, tosa e hospedagem na Barra — clientela premium, zero tolerância a demora",
    mensagem: `Oi! Vi o Pet Harmony na Barra — banho, tosa e hospedagem num dos bairros mais nobres do RJ.\n\nClientela da Barra tem ticket alto e pouca paciência pra esperar resposta. Como vocês estão gerenciando os pedidos que chegam fora do horário?\n\nÉ exatamente onde pet shop premium perde mais cliente de alto valor.`,
    notas: "Tel: (21) 99035-7191 | Barra da Tijuca — clientela premium | sem site",
    presencaDigital: "sem site | @petharmonyloja | telefone no Google: (21) 99035-7191 | Barra da Tijuca — clientela premium com expectativa de resposta rápida | presença média",
  },
  {
    nome: "A Pet Tosa",
    nicho: "pet shop", cidade: "Curicica, Rio de Janeiro",
    whatsapp: "5521979266915",
    site: "",
    instagram: "@apetitosabanhoetosa",
    canal: "whatsapp",
    problema: "Banho e tosa no RJ — WhatsApp ativo sem lembrete automático de retorno",
    mensagem: `Oi! Vi a A Pet Tosa no Rio — banho e tosa com WhatsApp de atendimento.\n\nUma pergunta simples: vocês têm algum sistema que lembra o tutor quando está na hora do próximo banho?\n\nSe não, tão deixando agendamento recorrente depender da memória do cliente — é receita que escapa toda semana.`,
    notas: "Tel: (21) 97926-6915 | Curicica RJ | sem site",
    presencaDigital: "sem site | @apetitosabanhoetosa | telefone no Google: (21) 97926-6915 | recorrência sem lembrete automático | presença média",
  },
  {
    nome: "Casa Canes Banho e Tosa",
    nicho: "pet shop", cidade: "Rio de Janeiro",
    whatsapp: "",
    site: "",
    instagram: "@casacanes",
    canal: "instagram",
    problema: "Banho e tosa no RJ — clientela recorrente 100% dependente de memória do tutor",
    mensagem: `Oi! Vi a Casa Canes — banho e tosa no Rio, boa presença no Instagram.\n\nCurioso: vocês têm algum sistema que avisa o tutor quando está na hora do próximo banho, ou ainda depende do cliente lembrar de ligar?\n\nÉ a diferença entre receita que chega sozinha e receita que você tem que correr atrás toda semana.`,
    notas: "Sem telefone e sem site | RJ | contato exclusivo via DM",
    presencaDigital: "sem site | @casacanes | contato exclusivo via Instagram DM | recorrência 100% dependente do tutor lembrar | presença fraca",
  },
  {
    nome: "Pet & Gatô BH",
    nicho: "pet shop", cidade: "Belo Horizonte",
    whatsapp: "553132139467",
    site: "",
    instagram: "@petegatobh",
    canal: "whatsapp",
    problema: "Pet shop com banho e tosa em BH — agendamento manual fora do expediente",
    mensagem: `Oi! Vi o Pet & Gatô em BH — banho e tosa com boa avaliação.\n\nPergunta direta: quando tutor manda mensagem pedindo horário fora do expediente, o que acontece com esse contato?\n\nÉ onde pet shop em BH perde mais agendamento sem perceber — não por falta de qualidade, por falta de resposta.`,
    notas: "Tel: (31) 3213-9467 | sem site | BH",
    presencaDigital: "sem site | @petegatobh | telefone no Google: (31) 3213-9467 | sem resposta automática fora do horário evidente | presença média",
  },
  {
    nome: "Caobeleireiro BH",
    nicho: "pet shop", cidade: "Belo Horizonte",
    whatsapp: "553133443860",
    site: "",
    instagram: "@caobeleireirobh",
    canal: "whatsapp",
    problema: "Estética animal, banho, tosa, creche e hospedagem — operação grande, triagem manual",
    mensagem: `Oi! Vi o Caobeleireiro em BH — estética, creche e hospedagem. Operação grande.\n\nCom tantos serviços chegando pelo WhatsApp ao mesmo tempo, como vocês estão priorizando e organizando cada pedido?\n\nÉ exatamente o tipo de operação onde automação de triagem e agendamento muda a rotina do dono.`,
    notas: "Tel: (31) 3344-3860 | estética + creche + hospedagem | operação grande | sem site",
    presencaDigital: "sem site | @caobeleireirobh | telefone no Google: (31) 3344-3860 | 4 serviços distintos — triagem manual ineficiente | presença média",
  },
  {
    nome: "Pet Móvel Beagá",
    nicho: "pet shop", cidade: "Belo Horizonte",
    whatsapp: "",
    site: "",
    instagram: "@petmovelbeaga",
    canal: "instagram",
    problema: "Banho na casa do cliente — modelo móvel, agendamento 100% no WhatsApp sem confirmação automática",
    mensagem: `Oi! Vi o Pet Móvel Beagá — banho na casa do tutor, modelo diferenciado em BH.\n\nOperação móvel significa que o agendamento é 100% pelo WhatsApp, certo? Como vocês estão organizando a agenda e confirmando os horários?\n\nÉ o tipo de operação que mais perde com processo manual — uma confirmação perdida é um buraco na rota do dia.`,
    notas: "Sem telefone e sem site | modelo móvel — rota diária | BH | contato via DM",
    presencaDigital: "sem site | @petmovelbeaga — modelo móvel | contato exclusivo via Instagram DM | agendamento 100% manual em rota diária — alta vulnerabilidade a no-show | presença fraca",
  },
  {
    nome: "Petland Campinas",
    nicho: "pet shop", cidade: "Campinas",
    whatsapp: "",
    site: "",
    instagram: "@petlandcampinas.avbrasil",
    canal: "instagram",
    problema: "Pet shop completo em Campinas — cidade grande, alto volume de atendimentos",
    mensagem: `Oi! Vi a Petland em Campinas — estrutura completa numa das maiores cidades do interior.\n\nCom esse volume, o agendamento de banho e tosa ainda é todo gerenciado pelo WhatsApp na mão?\n\nCampinas tem muito concorrente — quem responde mais rápido fica com o agendamento.`,
    notas: "Sem telefone e sem site | Campinas — mercado competitivo | contato via DM",
    presencaDigital: "sem site | @petlandcampinas.avbrasil | contato exclusivo via Instagram DM | Campinas — mercado competitivo | presença fraca",
  },

];

// ── Substitui todos os "encontrado" + preserva outras colunas ─
const existentes = JSON.parse(localStorage.getItem('pipeline_leads') || '[]');

// Mantém só os leads que já avançaram no pipeline
const jaAvancados = existentes.filter(l => l.status !== 'encontrado');

// Formata os novos leads pra "encontrado"
const novosFormatados = novosLeads.map((l, i) => ({
  id:              (Date.now() + i).toString(),
  nome:            l.nome,
  nicho:           l.nicho,
  cidade:          l.cidade,
  whatsapp:        l.whatsapp        || '',
  site:            l.site            || '',
  instagram:       l.instagram       || '',
  canal:           l.canal           || '',
  problema:        l.problema        || '',
  mensagem:        l.mensagem        || '',
  notas:           l.notas           || '',
  presencaDigital: l.presencaDigital || '',
  status:          'encontrado',
  criadoEm:        new Date().toISOString(),
}));

const total = [...novosFormatados, ...jaAvancados];
localStorage.setItem('pipeline_leads', JSON.stringify(total));

console.log(`✅ ${novosFormatados.length} leads na coluna Encontrado | ${jaAvancados.length} preservados em outras colunas`);
alert(`✅ Pipeline atualizado!\n\n${novosFormatados.length} leads novos na coluna "Encontrado"\n${jaAvancados.length} leads em outras colunas preservados\n\nRecarrega a página para ver.`);
